return {
  ["workshop-1247040097"]={
    configuration_options={
      backpack_ice=false,
      cage_frige=false,
      icebox_freeze="0",
      krampus_sack_ice=false,
      mushroom_frige=0.25,
      piggyback_ice=false,
      saltlicker=0 
    },
    enabled=true 
  },
  ["workshop-1898292532"]={
    configuration_options={
      antlion=true,
      atrium_gate=false,
      bearger=true,
      beequeenhive=false,
      crabking=false,
      deerclops=true,
      dragonfly=true,
      hound=true,
      klaus_sack=false,
      malbatross=false,
      tip_method=1,
      toadstool=false
    }
  },
  ["workshop-2283028733"]={
    configuration_options={
      amulet_slot=true,
      backpack_slot=true,
      chesspiece_fix=true,
      compass_slot=true,
      drop_bp_if_heavy=true,
      drop_hand_item_when_heavy=true,
      enable_ui=0,
      render_strategy="neck",
      show_compass=false,
      slot_num=0,
      snurtle_remove_armor=true
    },
    enabled=true
  },
  ["workshop-2287303119"]={
    configuration_options={
      [""]=0,
      T_crop=true,
      chestB=-1,
      chestG=-1,
      chestR=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="chs",
      show_food_units=-1,
      show_uses=1 
    },
    enabled=true 
  },
  ["workshop-2321974509"]={ configuration_options={ SIB=true, SSB=true }, enabled=true },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-375859599"]={
    configuration_options={
      divider=5,
      random_health_value=0,
      random_range=0,
      send_unknwon_prefabs=false,
      show_type=0,
      unknwon_prefabs=1,
      use_blacklist=true 
    },
    enabled=true 
  },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-543945797"]={
    configuration_options={
      amount_of_numbers="default",
      display_mode="waving",
      dmg_only="on",
      number_size="tiny",
      show_decimal_points="no" 
    },
    enabled=true 
  },
  ["workshop-797304209"]={ configuration_options={  }, enabled=true },
  ["workshop-831523966"]={
   configuration_options={soul_stack=20,stack_size=99},
   enabled=true
  }
}
